#!/usr/bin/env ruby

require 'sinatra/base'
require 'git'
require 'json'
require 'fileutils'
require 'pony'
require 'pp'

defaults = { 
  'bind' => '0.0.0.0',
  'port' => '4567',
  'logging' => true
}


if File.exist?(ARGV[0])
  OPTIONS = defaults.merge(YAML::load(File.open(ARGV[0])))
elsif Kernel.const_defined?(:TEST_OPTIONS)
  # We're testing
  OPTIONS = defaults.merge(YAML::load(TEST_OPTIONS || ""))
else
  $stderr.puts "Error: no configuration specified"
  exit 1
end

pp OPTIONS

class Deployd < Sinatra::Base
  set :bind, OPTIONS['bind']
  set :port, OPTIONS['port'].to_i
  set :logging, OPTIONS['logging']

  configure :production, :development do
    enable :logging
  end

  get '/' do
    content_type 'application/json'
    '{ "status": "ok" }' 
  end

  post '/deploy' do
    # send 412 Precondition Failed back if key not found
    if ! OPTIONS['keys'].include?(params['api_key'])
      logger.error "key #{params['api_key']} not found"
      halt 412, "Invalid credentials"
    end

    # send 412 Precondition Failed back if pass iznogoud
    if OPTIONS['keys'][params['api_key']]['secret'] != params[:api_secret]
      logger.error "key #{params['api_key']} found but password doesn't match"
      # logger.error "#{params['api_key'][:secret]} != params[:api_secret]"
      halt 412, "Invalid credentials"
    end

    logger.info "valid secret for key #{params[:api_key]} received"

    # retrieve branch
    puts request.env.inspect
    hook = JSON.parse request.env["rack.input"].read
    branch = hook["ref"].split("/",3)[2]

    # send 412 Precondition Failed back if pass iznogoud
    if ! OPTIONS['keys'][params['api_key']]['branches'].has_key?(branch)
      logger.error "directory for branch #{branch} not found"
      halt 412, "Directory for branch #{branch} not found"
    end

    path = File.expand_path(OPTIONS['keys'][params['api_key']]['branches'][branch])
    repos = hook["repository"]["name"]

    logger.info "checking directory #{path}"
    if Dir.exists?(path)
      g = Git.open(File.expand_path(path + "/" + repos),
                   :log => logger)
    else
      if ! Dir.exists?(path)
        logger.info "creating directory #{path}"
        FileUtils.mkdir_p(path)
      end
      logger.info "cloning #{hook["repository"]["url"]} in #{path}"
      g = Git.clone(hook["repository"]["url"], repos, :path => path)
    end

    commit_tag = hook["after"]

    logger.info "resetting to HEAD"
    g.reset_hard

    logger.info "pulling in #{path}"
    g.pull

    logger.info "resetting to commit #{commit_tag}"
    commit = g.gcommit(commit_tag)
    g.reset_hard commit

    if OPTIONS['keys'][params['api_key']].has_key?('notify')
      opts = { :to => OPTIONS['keys'][params['api_key']]['notify'],
               :subject => "Deployment notification for #{hook["repository"]["name"]}",
               :body => "Successfuly deployed #{hook['repository']['name']}/#{branch}/#{commit_tag} to #{path}"
      }.merge(PONY)
      logger.info "notifying #{OPTIONS['keys'][params['api_key']]['notify']}"
      Pony.mail(opts)
    end
  end
  run! if app_file == $0

end

