#!/bin/bash
# deployd    Init script for deployd
# chkconfig: 345 100 75
#
# Description: Starts and Stops Deployd, a sinatra web app listening to http post-commit hook calls
#

APP="deployd"
AS_USER="deploy"
APP_DIR="/var/www/${AS_USER}/${APP}"

APP_CONFIG="${APP_DIR}/config"
LOG_FILE="$APP_DIR/log/app.log"
LOCK_FILE="$APP_DIR/var/${APP}.lock"
PID_FILE="$APP_DIR/var/${APP}.pid"
GEMFILE="$APP_DIR/Gemfile"
APP_ENV="production"
PORT="4567"
BUNDLE="bundle"

START_CMD="$BUNDLE exec rackup -p ${PORT} -E ${APP_ENV} -P ${PID_FILE} deployd.rb"
CMD="cd ${APP_DIR}; ${START_CMD} >> ${LOG_FILE} 2>&1 &"

RETVAL=0


start() {

  status
  if [ $? -eq 1 ]; then

    [ -d $APP_DIR ] || (echo "$APP_DIR not found!.. Exiting"; exit 6)
    cd $APP_DIR
    echo "Starting $APP ruby application .. "

    su -c "$CMD" - $AS_USER

    RETVAL=$?
    #Sleeping for 8 seconds for process to be precisely visible in process table - See status ()
    sleep 8
    [ $RETVAL -eq 0 ] && touch $LOCK_FILE
    return $RETVAL
  else
    echo "$APP processor is already running .. "
  fi


}

stop() {

    echo "Stopping $APP ruby application .."
    SIG="INT"
    kill -$SIG `cat  $PID_FILE`
    RETVAL=$?
    [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
    return $RETVAL
}

status() {
  ps auwwx | grep '[r]uby.*rackup.*deployd.rb$' 
  return $?
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status

        if [ $? -eq 0 ]; then
             echo "$APP is running .."
             RETVAL=0
         else
             echo "$APP is stopped .."
             RETVAL=1
         fi
        ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 0
        ;;
esac
exit $RETVAL
