#!/bin/bash
#
# deployd    Init script for deployd
# chkconfig: 345 100 75
#
# Description: Starts and Stops Deployd, a sinatra web app listening to http post-commit hook calls
#

APP="deployd"
AS_USER="deploy"

PID_DIR="/var/run/"
APP_ENV="production"
BUNDLE="bundle exec"
APP_CONFIG="/etc/deployd.conf"

LOG_DIR="/var/log/${APP}/"
LOCK_FILE="${PID_DIR}/${APP}.lock"
PID_FILE="${PID_DIR}/${APP}.pid"
GEMFILE="$APP_DIR/Gemfile"

START_CMD="deployd"
CMD="cd ${APP_DIR}; ${START_CMD} >> ${LOG_DIR}/${APP_ENV}.log 2> ${LOG_DIR}/${APP_ENV}_error.log &"

RETVAL=0

if [ ! -e "${PID_DIR}" ]; then
  mkdir -p ${PID_DIR}
  chown ${AS_USER} ${PID_DIR}
fi

if [ ! -e "${LOG_DIR}" ]; then
  mkdir -p ${LOG_DIR}
  chown ${AS_USER} ${LOG_DIR}
fi

start() {
  status
  if [ $? -eq 1 ]; then

    [ -d $APP_DIR ] || (echo "$APP_DIR not found!.. Exiting"; exit 6)
    cd $APP_DIR
    echo "Starting $APP ruby application .."

    su -c "$CMD" - $AS_USER

    RETVAL=$?
    #Sleeping for 8 seconds for process to be precisely visible in process table - See status ()
    sleep 8
    [ $RETVAL -eq 0 ] && touch $LOCK_FILE
    return $RETVAL
  else
    echo "$APP is already running .."
  fi
}

stop() {

    echo "Stopping $APP .."
    SIG="INT"
    kill -$SIG `cat  $PID_FILE`
    RETVAL=$?
    [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
    return $RETVAL
}

status() {
  ps auwwx | grep '[r]uby.*deployd.*' 
  return $?
}


case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status

    if [ $? -eq 0 ]; then
      echo "$APP is running .."
      RETVAL=0
    else
      echo "$APP is stopped .."
      RETVAL=1
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|status}"
    exit 0
    ;;
esac

exit $RETVAL

